language: php

php:
    - 7.4
    - 8.0
    - 8.1

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer update
    - composer install

script:
    - ./vendor/bin/phpunit